version: '3'

services:
  #angular:
  #  #must run as sh, not bash due to alpine node
  #  command: sh docker-entrypoint.dev.sh

  django:
    command: bash docker-entrypoint.dev.sh
    environment:
      - DEVELOPMENT=true
      - POSTGRES_DB=fg_dev_db

  postgres:
    volumes:
      - ./postgres/scripts:/scripts
      - ./postgres/data:/data
    environment:
      - DEVELOPMENT=true
      - POSTGRES_USER=fg
      - POSTGRES_PASSWORD=qwer1234
      - POSTGRES_DB=fg_dev_db
