version: '2'

services:
  angular:
    #must run as sh, not bash due to alpine node
    command: sh docker-entrypoint.dev.sh

  django:
    command: bash docker-entrypoint.dev.sh
    environment:
      - DEVELOPMENT=true
      - POSTGRES_DB=fg_dev_db

  postgres:
    volumes:
      - ./postgres/scripts:/scripts
    environment:
      - DEVELOPMENT=true
      - POSTGRES_USER=fg
      - POSTGRES_PASSWORD=qwer1234
      - POSTGRES_DB=fg_dev_db
      - PGDATA=/var/lib/postgresql/data/pgdata